### ISSUE TITLE
NLP.zip is corrupt

### ISSUE THREAD

**Issue by faisalimran2018** [alanjeremiah/WLASL-Recognition-and-Translation#1]
The NLP.zip file is corrupt. Can you replace the file
![image](https://user-images.githubusercontent.com/19588729/171382246-c8bfbd28-151f-49bd-8043-ea533098454e.png)

**Comment by alanjeremiah** [comment]
You will be able to resolve this issue by downloading the NLP.zip file separately. Everything else should go smoothly, let me know if you need any help.

**Comment by shivamtawari** [comment]
Hi if you're not able to download the zip separately, you should try the following steps. I was able to download the NLP.zip from the below steps:

1. Fork the repo to one of your users
2. Go to repo settings
3. Find "Include Git LFS objects in archives" under the Archives section and check it
4. Go to the Danger Zone section, select "Archive this repository"
5. Confirm and authorize.
6. Return to the archived repository.
7. Download as .zip
8. Download will pause for a minute or so before it starts downloading lfs objects. Wait and it should continue.
