### ISSUE TITLE
The NLP.zip is corrupted

### ISSUE THREAD

**Issue by AbdulrhmanAlDahlan** [alanjeremiah/WLASL-Recognition-and-Translation#2]
I can't unzip the NLP.zip package its corrupted or damaged please upload it again

**Comment by Emile2022Codes** [comment]
@AbdulrhmanAlDahlan do you have access to the working version of NLP.zip ? if you would you be kind enough to send it to me

**Comment by jefferyjapheth** [comment]
I have the same issue with the NLP.zip package please upload it again.

**Comment by Ammareli** [comment]
same here

**Comment by alanjeremiah** [comment]
You can download the file from this link:

https://drive.google.com/file/d/1v8ym9ynUQ81Vz_I0nQr0y0bcenf2lloO/view?usp=sharing
