### ISSUE TITLE
Unable to Fetch nlp.zip due to Git LFS Quota Exceeded

### ISSUE THREAD

**Issue by shreyabhalgat** [alanjeremiah/WLASL-Recognition-and-Translation#6]
I am encountering an issue while trying to clone the repository and fetch the nlp.zip file due to a Git LFS quota exceeded error. Upon inspecting the raw file in the repository, I see the following Git LFS pointer:

version https://git-lfs.github.com/spec/v1
oid sha256:a66ba8f8a2a8bac6722cb0775a18c9206e2603aa8fd8ca6e3b5af4a8d3caa219
size 493238288
Since the repository has exceeded its data quota, I'm unable to access this file.

Steps to Reproduce:

Clone the repository: 
Attempt to fetch nlp.zip.
Expected Behavior:
I should be able to fetch the nlp.zip file without encountering a Git LFS quota exceeded error.

**Comment by alanjeremiah** [comment]
Will fix this, meanwhile you can download the file from this link:

https://drive.google.com/file/d/1v8ym9ynUQ81Vz_I0nQr0y0bcenf2lloO/view?usp=sharing
